name: 'Store Actions artifacts'
description: 'Wrapper for actions/upload-artifact, pinned to SHA'

inputs:
  path:
    description: 'Path to the file(s) to store'
    required: true
  name:
    description: 'Under what name should the artifact be stored'
    required: false
  if-no-files-found:
    description: 'What to return if there are no files (possible values: "warn", "error" and "ignore").'
    required: false
    default: 'warn'



runs:
  using: composite
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: ${{ inputs.path }}
        name: ${{ inputs.name }}
        if-no-files-found: ${{ inputs.if-no-files-found }}