name: Generate SBOM
description: Generate Software Bill of Materials using CycloneDX

inputs:
  version:
    description: 'Version to include in SBOM'
    required: true
  output-path:
    description: 'Output directory for SBOM'
    required: false
    default: '.'

# "--spec-version 1.5" Må endres til nyeste versjon når den er tilgjengelig i DT
runs:
  using: composite
  steps:
    - name: Generate SBOM
      shell: bash
      run: |
        dotnet new tool-manifest --force
        dotnet tool install CycloneDX
        SLNFILE=$(find . -name "*.sln" | head -1)
        if [ -n "$SLNFILE" ]; then
          dotnet tool run dotnet-CycloneDX \
            "$SLNFILE" \
            --output ${{ inputs.output-path }} \
            --set-version ${{ inputs.version }} \
            --spec-version 1.5 \
            --json
        else
          echo "No solution file found, skipping SBOM generation"
        fi
