name: 'Prepare JFrog CLI for Docker'
description: 'Sets up JFrog CLI, configures it with Artifactory, and logs in for Docker.'

inputs:
  artifactory_username:
    description: 'The username for Artifactory'
    required: true
  artifactory_password:
    description: 'The password for Artifactory'
    required: true
  docker_repo:
    description: 'An additional folder to which Docker needs access'
    required: false
    default: 'docker-all'

runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI
      uses: ks-no/github-actions-public/setup-jfrog-cli@main
      with:
        artifactory_username: ${{ inputs.artifactory_username }}
        artifactory_password: ${{ inputs.artifactory_password }}

    - name: Docker login
      shell: bash
      run: |
        echo "$RT_PWRD" | docker login "docker-all.artifactory.fiks.ks.no" -u "$RT_USER" --password-stdin
        if [ -n "$DOCKER_REPO" ] && [ "$DOCKER_REPO" != "docker-all" ] ; then
          echo "$RT_PWRD" | docker login "${DOCKER_REPO}.artifactory.fiks.ks.no" -u "$RT_USER" --password-stdin
        fi
      env:
        DOCKER_REPO: ${{ inputs.docker_repo }}
        RT_USER: ${{ inputs.artifactory_username }}
        RT_PWRD: ${{ inputs.artifactory_password }}
