name: OpenAPI Spec CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  open-api-spec-ci:
    uses: ks-no/github-actions-public/.github/workflows/open-api-specs.yml@main
    with:
      specs_folder: 'specs'
    secrets: inherit
