name: Zizmor Security Audit
description: Scans GitHub Actions workflow files for security vulnerabilities using zizmor. Runs automatically on every push and pull request.

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  audit:
    uses: ks-no/github-actions-public/.github/workflows/zizmor-audit.yml@main
    with:
      # Optional: hvis github advanced security er konfigurert kan man få outputten i github security tab ved å bruke sarif.
      # Defaulter til 'github', hvis ingenting er satt slik at det vises i github summary.
      # output_format: sarif 
