# Starter workflow for zizmor.
name: Zizmor Security Audit

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    uses: ks-no/github-actions-public/.github/workflows/zizmor-audit.yml@main
